- name: install php-fpm
  yum: name={{ item }} state=present
  with_items:
    - php70
    - php70-fpm
    - php70-mcrypt
    - php70-cli
    - php70-common
    - php70-devel
    - php70-mbstring
    - php70-mysqlnd
    - php70-opcache
    - php70-pdo
    - php70-pecl-apcu
    - php70-process
    - php70-xml
    - php70-gd

- name: Configure php.ini
  template: src=php.ini dest=/etc/php.ini owner=root group=root mode=0644
  notify: restart nginx

- name: copy /etc/php-fpm.d/
  copy: src=etc/php-fpm.d/ dest=/etc/php-fpm.d/ backup=yes
  notify: restart php-fpm

- name: start php-fpm
  service: name=php-fpm state=started enabled=yes

- name: copy /etc/nginx/default.d/
  copy: src=etc/nginx/default.d/ dest=/etc/nginx/default.d/ backup=yes
  notify: restart nginx

## Common Conifgration ( CloudWatch Logs & Datadog Integration & logrotate )

- name: copy {{ awslogs_config_dir_path }}config
  copy: src=etc/awslogs/config/ dest={{ awslogs_config_dir_path }}config/ backup=yes
  notify: restart awslogs agent

- name: copy /etc/logrotate.d/
  copy: src=etc/logrotate.d/ dest=/etc/logrotate.d/
