## Install and Configuration
- name: yum install for Apache Web Server
  yum: name=httpd24

- name: Start and Enable to Apache
  service: name=httpd state=started enabled=yes

- name: copy /etc/httpd/conf.d/
  copy: src=common/etc/httpd/conf.d/ dest=/etc/httpd/conf.d/ backup=yes
  notify: restart httpd

- name: Makes to VirtualHost
  template: src=virtualhost.conf dest=/etc/httpd/conf.d/{{ item.domain }}.conf
  with_items:
    - "{{ site | default([]) }}"
  notify: restart httpd

- name: Makes to VirtualHost DocumentRoot
  file: path=/var/www/{{ item.domain }} state=directory owner={{ item.owner }} group={{ item.group }} mode=0755
  with_items:
    - "{{ site | default([]) }}"

## Copy Apache Conf
- name: Change the httpd.conf to template file ( Apache 2.4 )
  copy: src=ver2.4/etc/httpd/ dest=/etc/httpd/ owner=root group=root mode=0644
  notify: restart httpd

- name: logrotate ( Apache 2.4 )
  copy: src=ver2.4/etc/logrotate.d/ dest=/etc/logrotate.d/ owner=root group=root mode=0644

- name: monit ( CentOS7 Apache 2.4 )
  copy: src=ver2.4/etc/monit.d/ dest=/etc/monit.d/ owner=root group=root mode=0644

## Common Conifgration ( CloudWatch Logs & logrotate )
- name: copy VirtualHost Log setting to {{ awslogs_config_dir_path }}
  template: src=awslogs.conf dest={{ awslogs_config_dir_path }}config/apache-{{ item.domain }}.conf backup=yes
  with_items:
    - "{{ site | default([]) }}"
  notify: restart awslogs agent

- name: copy Default Log setting to {{ awslogs_config_dir_path }}
  template: src=awslogs-default.conf dest={{ awslogs_config_dir_path }}config/apache-default.conf backup=yes
  notify: restart awslogs agent