- name: Install php package
  yum: name={{ item }} state=present
  with_items:
    - php56
    - php56-cli
    - php56-pdo
    - php56-mbstring
    - php56-mcrypt
    - php56-pecl-memcache
    - php56-mysqlnd
    - php56-devel
    - php56-common
    - php56-pgsql
    - php-pear
    - php56-gd
    - php56-xml
    - php56-pecl-apc
  notify: restart httpd

- name: Configure php.ini
  template: src=php.ini dest=/etc/php.ini owner=root group=root mode=0644
  notify: restart httpd

- name: check exists PHP Composer
  stat: path="/usr/local/bin/composer"
  register: check_composer_file

#- name: Install PHP Composer
#  shell: |
#    cd ~
#    /usr/bin/curl -sS https://getcomposer.org/installer | /usr/bin/php
#    mv ~/composer.phar /usr/local/bin/composer
#  when: not check_composer_file.stat.exists
